[package]
name = "lyric_finder"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "A lyric finder library"
authors = ["Thang Pham <phamducthang1234@gmail.com>"]
repository = "https://github.com/aome510/spotify-player/tree/master/lyric_finder"
keywords = ["lyric", "song", "track"]

[dependencies]
anyhow = "1.0.69"
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
html5ever = "0.26.0"
markup5ever_rcdom = "0.2.0"
log = "0.4.17"

[dev-dependencies]
tokio = { version = "1.25.0", features = ["rt", "rt-multi-thread", "macros"] }
env_logger = "0.10.0"

[[example]]
name = "lyric-finder"
path = "examples/lyric-finder.rs"
